version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      ELASTIC_USERNAME: "root"
      ELASTIC_PASSWORD: "P@$$w0rd"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    networks:
      - elkstack
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  logstash:
    image: logstash:7.17.18
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - ./configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./configs/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 5044:5044
      - 5046:5046 # для Filebeat
      - 9600:9600 # monitoring
    depends_on:
      - elasticsearch
    networks:
      - elkstack

  kibana:
    image: kibana:7.17.18
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elkstack

  filebeat:
    image: elastic/filebeat:7.17.18
    container_name: filebeat
    user: root
    command: filebeat -e --strict.perms=false
    depends_on:
      - logstash
    volumes:
      - ./configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elkstack

  application:
    image: python:3.9-alpine
    container_name: app
    volumes:
      - ./pinger:/opt
    entrypoint: python3 /opt/run.py
    networks:
      - elkstack

volumes:
  esdata:

networks:
  elkstack:
    driver: bridge
