FROM debian:latest

ENV DEBIAN_FRONTEND=noninteractive

# Установка необходимых пакетов
RUN apt-get update && apt-get install -y \
    openssh-server \
    sudo \
    python3 \
    python3-pip \
    iputils-ping \
    iproute2 \
    net-tools \
    curl \
    wget \
    traceroute \
    dnsutils \
    vim \
    less \
    procps \
    dnf \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Настройка SSH
RUN mkdir /var/run/sshd

# Создание пользователя ansible с паролем ansible и правами sudo без пароля
RUN useradd -m ansible && echo "ansible:ansible" | chpasswd && \
    echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Разрешить вход по SSH с паролем
RUN sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/bin/bash"]