{
 "title": "Netology 03",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Memory",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=~\"ext4|xfs\"}",
     "legendFormat": "DiskMemAvailable in /"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}",
     "legendFormat": "DiskMemTotal in /"
    }
   ]
  },
  {
   "title": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[1m])) * 100",
     "legendFormat": "Утилизация CPU для nodeexporter"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}",
     "legendFormat": "MemoryFree"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"nodeexporter\"})",
     "legendFormat": "CPULA1"
    },
    {
     "expr": "avg(node_load5{job=\"nodeexporter\"})",
     "legendFormat": "CPULA5"
    },
    {
     "expr": "avg(node_load15{job=\"nodeexporter\"})",
     "legendFormat": "CPULA15"
    }
   ]
  }
 ]
}